title: Adrian Tan
logo: "/images/profilePicture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from UC Berkeley with Bachelor of Arts in Computer Science major, and I'm now a EECS 5-th year masters at University of California, Berkeley. My main focus is on computer graphics.
  <br><br>
  I'm interning at Nvidia as a Raytracing Engineer for Nvidia Omniverse. I was a Graphics Engineering Intern at Blizzard Entertainment during summer 2020, working and prototyping on raytracing GI solutions in the Shared Game Engine team.
  <br><br>
  
  <a href="https://www.linkedin.com/in/adriantanteckkeng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
