title: Adrian Tan
logo: "/images/profilePicture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from the National University of Singapore with a Bachelor of Engineering in Engineer Science. I'm now a a 5-th year Ph.D. student at Caltech working on applications of near-term quantum computers, specifically to use them to simulate materials.
  <br><br>
  Recently, I discovered I have an interest in computer graphics and image processing and have started working on some projects in these areas outside of research. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/adriantanteckkeng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
