title: Adrian Tan
logo: "/images/profilePicture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from UC Berkeley with Bachelor of Arts in Computer Science major.
  <br><br>
  Second description 
  <br><br>
  
  <a href="https://www.linkedin.com/in/adriantanteckkeng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
