title: Adrian Tan
logo: "/images/profilePicture.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from UC Berkeley with Bachelor of Arts in Computer Science major, and I'm now a EECS 5-th year masters at University of California, Berkeley. My main focus is on computer graphics.

I'm interning at Nvidia as a Raytracing Engineer for Nvidia Omniverse. I was a Graphics Engineering Intern at Blizzard Entertainment during summer 2020, working and prototyping on raytracing GI solutions in the Shared Game Engine team.

My field of interest is mainly computer graphics, especially real-time rendering. You can check out lots of my cool projects on this field, and I have an especially strong passionate in games and visual medium.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/adriantanteckkeng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
