title: Adrian Tan
description: > # your text below (remove <br> elements if you don't need line breaks)
  I graduated from the National University of Singapore with a Bachelor of Engineering in Engineering Science. I'm now a a 5th year Ph.D. student at Caltech working on applications of near-term quantum computers, specifically for the purpose of simulating materials.
  <br><br>
  More recently, I discovered an interest in computer graphics and image processing and have begun working on exploratory projects outside of research. You can see some of them here!
  <br><br>
  
  <a href="https://www.linkedin.com/in/adriantanteckkeng/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
